logging.level.de.malkusch: DEBUG
trashday:
   url: https://apps.c-trace.de/web.roth/abfallkalender/cal?Ort=Hilpoltstein&Ortsteil=Weinsfeld&Strasse=Weinsfeld&Hausnr=K%2034
prometheus:
   url: http://localhost:9090
dehumidifier:
   tasmota:
   -  name: keller
      power: 250
      url: http://tasmota-1
buderus:
   gatewayPassword: 1234-1234-1234-1234
   privatePassword: 1234
   host: heizung
sonnen:
   url: http://192.168.0.123:8080/api/v1/status
notification:
   telegram:
      token: aToken
      chatId: 1234