logging.level.de.malkusch: DEBUG
trashday:
   url: https://apps.c-trace.de/web.roth/abfallkalender/cal?Ort=Hilpoltstein&Ortsteil=Weinsfeld&Strasse=Weinsfeld&Hausnr=K%2034
prometheus:
   url: http://localhost:9090
dehumidifier:
   tasmota:
   -  name: keller
      power: 250
      url: http://tasmota-1
buderus:
   gatewayPassword: 1234-1234-1234-1234
   privatePassword: 1234
   host: heizung
sonnen:
   url: http://192.168.0.2:8080/api/v1/status
monitoring:
   sensors:
   -  name: bad
      url: http://bad/
   -  name: keller
      url: http://klima1/
   -  name: keller2
      url: http://xxx/
   -  name: klima3
      url: http://klima3/
   -  name: co2
      url: http://co2/
notification:
   telegram:
      token: aToken
      chatId: 1234