logging.level.de.malkusch: DEBUG
prometheus:
   url: http://localhost:9090
   climate:
      outside-prefix: aussen
      rooms:
         - room: keller
           prefix: kellerSensors
dehumidifier:
   tasmota:
   -  name: keller
      room: keller
      power: 250
      desired-humidity:
         minimum: 0.40
         maximum: 0.50
      url: http://tasmota-1
room:
   rooms:
      - id: keller
        signal-light: ec:0b:ae:50:f9:c2
shutters:
   shelly:
      url: https://shelly-31-eu.shelly.cloud
      key: 123abc
      shutters:
       - id: KUECHENTUER
         device-id: 123abc
         direct-sun-light:
            start: 10
            end: 20
      blinds:
       - id: WOHNZIMMER_KLEIN
         device-id: 456
         direct-sun-light:
            start: 12
            end: 22
buderus:
   gatewayPassword: 1234-1234-1234-1234
   privatePassword: 1234
   host: http://heizung
location:
   latitude: 12.3
   longitude: 45.6
open-weather:
   api-key: 123abc
notification:
   telegram:
      token: aToken
      chatId: 1234