logging.level.de.malkusch: DEBUG
prometheus:
   url: http://localhost:9090
dehumidifier:
   tasmota:
   -  name: keller
      power: 250
      url: http://tasmota-1
notification:
   telegram:
      token: aToken
      chatId: 1234