logging.level.de.malkusch: DEBUG
prometheus:
   url: http://localhost:9090
dehumidifier:
   tasmota:
   -  name: keller
      power: 250
      url: http://tasmota-1
buderus:
   gatewayPassword: 1234-1234-1234-1234
   privatePassword: 1234
   host: heizung
notification:
   telegram:
      token: aToken
      chatId: 1234