logging.level.de.malkusch.ha.shared.infrastructure.buderus: INFO
scheduler:
   delay: PT60s
dehumidifier:
   rules:
      buffer: 50
      window: PT30m
      evaluationRate: PT10m
room:
   rules:
      open-window:
         evaluationRate: PT2m
         co2-threshold:
            best: 500
            old: 1500
            unhealthy: 2500
         dust-buffer-pm25: 3
shutters:
   minimum-highest-daily-temperature: 25
   cold-night-temperature: 21
   delay: PT0.2s
   wind-protection:
      release-wind-speed: 30
      protect-wind-speed: 35
      protection-state: 100
      lock-duration: PT12h
      evaluation-rate: PT15m
   shelly:
      url: https://shelly-31-eu.shelly.cloud
      key: 123abc
      shutters:
       - id: KUECHENTUER
         device-id: 123abc
   blinds:
      wind-protection:
         release-wind-speed: 20
         protect-wind-speed: 25
         protection-state: 0
         lock-duration: PT12h
electricity:
   battery:
      fully-charged: 0.96
   prediction:
      minimumPeak: 4000
      peakWindow: P14D
      learning-window: P14D
      learn-cron: 59 55 3 * * * # Daily at 3:55:59
      qa:
         predict-cron: 59 59 * * * * # Every hour
         evaluate-cron: 59 55 6 * * * # Daily at 6:55:59
   wallbox:
      minimum-loading-consumption: 4000
      minimum-loading-duration: PT30m
   scooter:
      wallbox:
         tuya-socket:
            timeout: PT5s
            expiration: PT15m
            discover-cron: 59 */30 * * * * # Every half an hour
         cool-down: PT30m
         balancing-threshold: 0.95
      charging-rule:
         evaluation-rate: PT15m
         minimum-charge:
            start: 0.4
            stop: 0.5
         maximum-charge: 0.8
         excess-charging:
            window: PT30m
            start-excess: 1000
            stop-excess: 200
            start-charge: 0.7
         
buderus:
   salt: 867845e97c4e29dce522b9a7d3a3e07b152bffadddbed7f5ffd842e9895ad1e4
   queryRate: PT1m
   timeout: PT10s
   hot-water:
      rules:
         reset-program:
            evaluation-rate: PT30m 
         reduce-in-winter:
            evaluation-rate: PT6h 
            cloudiness-threshold: 0.75
            delta: 3
   heater:
      external-reset-temperature-check-cron: 59 */30 * * * * # Every 30 minutes
      rules:
         window: PT30m
         evaluationRate: PT30m
         increase:
            threshold: 1500
            temperature: 22
         reset:
            threshold: 500
      temporary-day-temperature:
         steps: 2
         step: 0.5
      avoid-grid-rule:
         min-capacity: 0.10
         max-cloudiness: 0.75
         excess-threshold: 500
         evaluationRate: PT30m
location:
   latitude: 123
   longitude: 123
open-meteo:
   forecast:
      refresh-cron: 59 */15 * * * * # Every 15 minutes
http:
   timeout: PT10S
   userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
   retry:
      delay: PT5S
      retries: 10
