scheduler:
   delay: PT20s
dehumidifier:
   rules:
      turnOn:
         buffer: 50
         window: PT30m
         evaluationRate: PT10m
      turnOff:
         window: PT30m
         evaluationRate: PT10m
prometheus:
   delay: PT21s
http:
   timeout: PT10S
   userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
   retry:
      delay: PT5S
      retries: 5