logging.level.de.malkusch.ha.shared.infrastructure.buderus: INFO
scheduler:
   delay: PT60s
dehumidifier:
   rules:
      buffer: 50
      window: PT30m
      evaluationRate: PT10m
shutters:
   delay: PT0.2s
   wind-protection:
      release-wind-speed: 25
      protect-wind-speed: 35
      protection-state: 100
      lock-duration: PT12h
   shelly:
      url: https://shelly-31-eu.shelly.cloud
      key: 123abc
      shutters:
       - id: KUECHENTUER
         device-id: 123abc
   blinds:
      wind-protection:
         release-wind-speed: 10
         protect-wind-speed: 20
         protection-state: 0
         lock-duration: PT12h
      terrasse:
         night-close-threshold: 20
buderus:
   salt: 867845e97c4e29dce522b9a7d3a3e07b152bffadddbed7f5ffd842e9895ad1e4
   queryRate: PT1m
   timeout: PT10s
   hot-water:
      rules:
         reset-program:
            evaluation-rate: PT30m 
         reduce-in-winter:
            evaluation-rate: PT6h 
            cloudiness-threshold: 0.75
            delta: 3
   heater:
      temporary-day-temperature:
         steps: 2
         step: 0.5
      avoid-grid-rule:
         min-capacity: 0.10
         max-cloudiness: 0.75
         excess-threshold: 500
         evaluationRate: PT30m
location:
   latitude: 123
   longitude: 123   
open-weather:
   base-url: https://api.openweathermap.org/data/2.5/onecall
   api-key: 123abc
   refresh-cron: 59 */10 * * * * # Every ten minutes
monitoring:
   updateRate: PT15s
   timeout: PT3S
   retries: 2
http:
   timeout: PT10S
   userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
   retry:
      delay: PT5S
      retries: 10