logging.level.de.malkusch.ha.shared.infrastructure.buderus: INFO
scheduler:
   delay: PT20s
dehumidifier:
   rules:
      buffer: 50
      window: PT30m
      evaluationRate: PT10m
buderus:
   salt: 867845e97c4e29dce522b9a7d3a3e07b152bffadddbed7f5ffd842e9895ad1e4
   queryRate: PT1m
   timeout: PT10s
monitoring:
   updateRate: PT15s
   timeout: PT3S
prometheus:
   delay: PT21s
http:
   timeout: PT10S
   userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
   retry:
      delay: PT5S
      retries: 10