# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build jar
      run: mvn verify
    - name: Save jar
      uses: actions/upload-artifact@v2
      with:
        name: homeautomation.jar
        path: target/homeautomation.jar
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Restore artifact
        uses: actions/download-artifact@v2
        with:
            name: homeautomation.jar
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: homeautomation.jar
            asset_name: homeautomation.jar
            tag: ${{ github.ref }}-snapshot
            overwrite: true
